### ISSUE TITLE
tests run only in Nodejs@14

### ISSUE THREAD

**Issue by inacior** [inacior/is-my-env-alive#9]
The tests are running only in Nodejs 14.x.
They should run in 10.x, 12.x and 14.x

**Comment by markomarkovic** [comment]
Actually, they run in at least `v13.14.0` too :)

**Comment by inacior** [comment]
> Actually, they run in at least `v13.14.0` too :)

Yes! but the Github actions runs on 10.x, 12.x and 14.x
